# Generated by Django 5.2.3 on 2025-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_busparking_delete_reisebusparking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorhomeParking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("capacity", models.CharField(max_length=100)),
                ("cost", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
        ),
    ]
