# Generated by Django 5.2.3 on 2025-06-27 09:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_culturalsite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="culturalsite",
            old_name="wheelchair_access",
            new_name="wheelchair",
        ),
        migrations.RemoveField(
            model_name="culturalsite",
            name="osm_id",
        ),
        migrations.AddField(
            model_name="culturalsite",
            name="wikidata",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="culturalsite",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="culturalsite",
            name="name",
            field=models.CharField(default="Unnamed Site", max_length=255),
            preserve_default=False,
        ),
    ]
