# Generated by Django 5.2.3 on 2025-06-27 09:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_wheelchair_access_culturalsite_wheelchair_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="culturalsite",
            old_name="wikidata",
            new_name="wheelchair_access",
        ),
        migrations.RemoveField(
            model_name="culturalsite",
            name="wheelchair",
        ),
        migrations.AddField(
            model_name="culturalsite",
            name="osm_id",
            field=models.CharField(default="undefined", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="culturalsite",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="culturalsite",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
