# Generated by Django 5.2.3 on 2025-06-27 17:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_wikidata_culturalsite_wheelchair_access_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("area", models.FloatField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        geography=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
