# Generated by Django 5.2.3 on 2025-06-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_administrativedistrict"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativedistrict",
            name="area",
        ),
        migrations.RemoveField(
            model_name="administrativedistrict",
            name="population",
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="area_km2",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="district_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="kggs",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="object_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="shape_area",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="shape_length",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="administrativedistrict",
            name="short_code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="administrativedistrict",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
