# Generated by Django 5.2.3 on 2025-06-27 19:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_administrativedistrict_area_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaxonCulturalSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("tourism", models.CharField(blank=True, max_length=100, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                ("building", models.CharField(blank=True, max_length=100, null=True)),
                ("wheelchair", models.CharField(blank=True, max_length=50, null=True)),
                ("wikidata", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        geography=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
