# Generated by Django 5.2.3 on 2025-06-28 15:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_saxonculturalsite"),
    ]

    operations = [
        migrations.AddField(
            model_name="busparking",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="motorhomeparking",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
    ]
